# Generated by Django 4.2 on 2023-05-17 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.IntegerField()),
                ('orderId', models.IntegerField()),
                ('intendTime', models.CharField(max_length=255)),
                ('startTime', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shipping')),
            ],
        ),
    ]
